title: Web Roadmap Developer 2020
lang: en
description: Material de estudo sobre minhas trilhas do Web Roadmap Developer 2020

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true
